"""Update UserType enum to include RE_SALES_ADVISOR

Revision ID: e54047eee1a6
Revises: 
Create Date: 2025-09-11 07:53:06.360974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54047eee1a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.alter_column('land_parcels', 'landowner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('land_parcels', 'landowner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    # ### end Alembic commands ###
